#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- HopeMbtiQ
model<-"
! regressions 
   MBTI=~MBTI__EI*EI
   MBTI=~MBTI__NS*NS
   MBTI=~MBTI__FT*FT
   MBTI=~MBTI__JP*JP
   HOPE=~HOPE__A1*A1
   HOPE=~HOPE__A2*A2
   HOPE=~HOPE__A3*A3
   HOPE=~HOPE__A4*A4
   HOPE=~HOPE__P1*P1
   HOPE=~HOPE__P2*P2
   HOPE=~HOPE__P3*P3
   HOPE=~HOPE__P4*P4
   MBTI=~MBTI__HOPE*HOPE
! residuals, variances and covariances
   EI ~~ VAR_EI*EI
   NS ~~ VAR_NS*NS
   FT ~~ VAR_FT*FT
   JP ~~ VAR_JP*JP
   A1 ~~ VAR_A1*A1
   A2 ~~ VAR_A2*A2
   A3 ~~ VAR_A3*A3
   A4 ~~ VAR_A4*A4
   P1 ~~ VAR_P1*P1
   P2 ~~ VAR_P2*P2
   P3 ~~ VAR_P3*P3
   P4 ~~ VAR_P4*P4
   MBTI ~~ 1.0*MBTI
   HOPE ~~ 1.0*HOPE
! observed means
   EI~1;
   NS~1;
   FT~1;
   JP~1;
   A1~1;
   A2~1;
   A3~1;
   A4~1;
   P1~1;
   P2~1;
   P3~1;
   P4~1;
";
result1 <- lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
result1b <- lavaan(model, data=modelData, fixed.x=FALSE, missing="listwise", estimator = "DWLS");
summary(result1, fit.measures=TRUE);
summary(result1b, fit.measures=TRUE);
semTable(list("Model 1" = result1 , "Model 2" = result1b),
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Statistical Estimated Parameters for the Personality-Leadership Structural Model",
         label = "t3")

